### ISSUE TITLE
Crash when trying to access records

### ISSUE THREAD

**Issue by ghost** [DDoSolitary/GreenDragonfly#1]
It responds really slow when sliding on the listview and moreover, when it reaches the 26<sup>th</sup> piece of record, the application crashes. Same problem doesn't disappear after rebooting the phone or reinstalling the application.
Since I have no idea about debugging an Android application, I just exported the crash log.
I'm currently using MI6 running MIUI10 9.7.11 Beta(Android version 9) and GreenDragonfly v1.1.3.

[Here is the log exported](https://github.com/DDoSolitary/GreenDragonfly/files/3855213/greendragonfly.log)

Anyway, thank you for you time.

**Comment by DDoSolitary** [comment]
Thanks for reporting this. It seems that the error occurred when the app was trying to decrypt the record data stored in the database but found the data corrupted. I've got a similar report from one of my friends. But unfortunately I'm unable to reproduce this issue on my Android 9 and 10 phones and I have no idea why the data got corrupted. Currently I'm considering catch this exception and automatically delete the corrupted records.

For now if you want to continue to use the app you can just **uninstall** and then reinstall the app. All of your records will be lost but the upload counter will be properly kept on the school's server.

**Comment by ghost** [comment]
Sorry for making such mistake that I didn't reinstall the app correctly.
The problem have been solved by uninstalling and reinstalling.
Again, thank you for your effort.

**Comment by DDoSolitary** [comment]
BTW, as for the slow scrolling problem, it seems that it is because the decryption result isn't cached and gets re-calculated every time a record is accessed. A fix will be released soon.
