### ISSUE TITLE
multiple upload

### ISSUE THREAD

**Issue by Narukara** [DDoSolitary/GreenDragonfly#16]
user can upload more than one record in one day from **different devices**

---

device 1 :

![65SN3 0 ZO $)ENMQU2J4%0](https://user-images.githubusercontent.com/53737377/97804947-e6053700-1c8d-11eb-8481-70d81b5c18ac.png)

---

device 2 :

![B9A8RAVD~@KSI%F@ K~6$JS](https://user-images.githubusercontent.com/53737377/97804959-f87f7080-1c8d-11eb-9810-3c77da3ad039.png)

**Comment by Narukara** [comment]
maybe there is no suitable API on the server

**Comment by DDoSolitary** [comment]
Yes, the upload API will always return a successful message even if the requirements are not met, but the counter will not increase in that case.

**Comment by DDoSolitary** [comment]
As the server doesn't provide any interface to retrieve the already uploaded records, I don't think detection can be easily implemented on client side.
